# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogpost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=100)),
                ('blog_id', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('post_date', models.DateField()),
            ],
        ),
    ]
