# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 07:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100, verbose_name='Showed in web page')),
                ('tag_id', models.CharField(max_length=100, verbose_name='Showed in URL')),
            ],
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='post_date',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='tag',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tag',
            field=models.ManyToManyField(to='blog.Tag'),
        ),
    ]
